volumes:
  server-node-modules:
  client-node-modules:


services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: base
    container_name: server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app/server
      - server-node-modules:/app/server/node_modules
    env_file:
      - path: ./server/.env
        required: false
    working_dir: /app/server
    command: pnpm run start:dev

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: development
    container_name: client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app/client
      - client-node-modules:/app/client/node_modules
    environment:
      - DOCKER_CONTAINER=true
    working_dir: /app/client
    command: sh -c "pnpm install && pnpm run dev"
    depends_on:
      - server
